### ISSUE TITLE
Review generics

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast-incubator/spring-data-integrations-commons#19]
In ``org.springframework.data.hazelcast.repository.HazelcastRepository`` the signfature is:
```
public interface HazelcastRepository<T, ID extends Serializable> extends KeyValueRepository<T, ID> {}
```

For Spring Data, the ``ID`` is a field in the domain object ``T``.
For Hazelcast the domain object has to be serializable.

**Comment by gAmUssA** [comment]
Btw, is it a hard requirement on the signature? 
Sometimes domain object can be `DataSerializable` or `IdentifiedDataSerializable` or `Portable`

**Comment by neilstevenson** [comment]
My opinion is it breaks the abstraction if "``import com.hazelcast....``" is in the application layer.
The application should know about Spring but not Hazelcast.

Nevertheless, the performance gains from the Hazelcast serialization types could be useful.

**Comment by gAmUssA** [comment]
but we don't need to add this to the signature
